version: '3'
services:

  nginx:
    image: nginx:1.25.3
    container_name: dlt-green.nginx
    restart: unless-stopped
    volumes:
      - ./web:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "proxy.constraint=dlt-green"

      - "traefik.http.routers.nginx.service=nginx"
      - "traefik.http.routers.nginx.rule=Host(`${DLTGREEN_HOST:?DLTGREEN_HOST is missing}`) && PathPrefix(`/`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"

      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.services.nginx.loadbalancer.healthCheck.path=/"
      - "traefik.http.services.nginx.loadbalancer.healthCheck.interval=15s"
      - "traefik.http.services.nginx.loadbalancer.healthCheck.timeout=5s"

      - "traefik.http.routers.nginx.middlewares=security-headers"

      # middlewares
      - "traefik.http.middlewares.security-headers.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.Access-Control-Allow-Origin=https://${DLTGREEN_HOST:?DLTGREEN_HOST is missing}:${DLTGREEN_HTTPS_PORT:-443}"
      - "traefik.http.middlewares.security-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.security-headers.headers.addvaryheader=true"
      - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  ##################################################################
  #  Reverse Proxy and SSL                                         #
  ##################################################################

  traefik:
    image: traefik:v2.11
    container_name: dlt-green.traefik
    restart: unless-stopped
    env_file:
      - .env
    command:
      - "--log.level=WARN"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`proxy.constraint`,`dlt-green`)"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=10"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=10"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=10"
      - "--entrypoints.websecure.transport.respondingTimeouts.writeTimeout=10"

      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL:-}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "${DLTGREEN_HTTP_PORT:-80}:80/tcp"
#      - "${DLTGREEN_HTTPS_PORT:-443}:443/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${DLTGREEN_DATA_DIR:-./data}/letsencrypt:/letsencrypt"
      - "./assets/traefik:/etc/traefik/dynamic:ro"
      - "${DLTGREEN_SSL_CERT:-./assets/traefik/certs/fake.cert}:/certs/domain.cert:ro"
      - "${DLTGREEN_SSL_KEY:-./assets/traefik/certs/fake.key}:/certs/domain.key:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  default:
    name: dlt-green
    external: true
